sudo: require

services:
  - docker

script:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";

    export REPO=$DOCKER_USERNAME/jatumba-frontend;
    docker build -t $REPO:$TRAVIS_COMMIT .;
    docker tag $REPO:$TRAVIS_COMMIT $REPO:latest;
    docker push $REPO:latest;
    fi
